# asset pack configurations
[asset_pack]
	# asset pack name
	name =				"falaxir-polygons"
	# contributors
	author =			"Falaxir"
	# version
	version =			"1.0.0"
	# image URL
	image =				"https://falaxir.fr/images/nanos/quake-polygons.jpg"
	# unreal engine folder - the name of the root folder (the one inside UnrealProject/Content/) which the assets will have references to each other
	unreal_folder =		"falaxir-polygons"

# assets files
[assets]
	# maps
	[assets.maps]
		Polygons = "Maps/Polygons"

	# static meshes
	[assets.static_meshes]
		MapMesh = "Meshes/MapMesh"

	# skeletal meshes
	[assets.skeletal_meshes]
		# SK_Better_Man = "Characters/SK_BetterMan_03"
		# ...

	# sounds
	[assets.sounds]
		# A_Awesome_Music = "Sounds/A_Awesome_Music"
		# ...

	# animations
	[assets.animations]
		# A_Character_Jump = "Animations/A_Character_Jump"
		# ...

	# particles
	[assets.particles]
		# P_Big_Explosion = "Particles/P_Big_Explosion"
		# ...

	# other assets (for not yet categorized ones)
	[assets.others]
		# A_Audio_Rifle_Fire = "Audios/A_Audio_Rifle_Fire_03"
		# ...
